// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace demoNetCore.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    partial class ApplicationDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("demoNetCore.Models.Demo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Demotable");
                });

            modelBuilder.Entity("demoNetCore.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employee ");
                });

            modelBuilder.Entity("demoNetCore.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonName")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonID");

                    b.ToTable("Person");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("demoNetCore.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductID");

                    b.ToTable("Product ");
                });

            modelBuilder.Entity("demoNetCore.Models.Student", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentName")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("demoNetCore.Models.tes1", b =>
                {
                    b.Property<string>("tes1ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("tes1Name")
                        .HasColumnType("TEXT");

                    b.HasKey("tes1ID");

                    b.ToTable("tes1s");
                });

            modelBuilder.Entity("demoNetCore.Models.tes2", b =>
                {
                    b.Property<string>("ProducttID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProducttName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("tes1ID")
                        .HasColumnType("TEXT");

                    b.HasKey("ProducttID");

                    b.HasIndex("tes1ID");

                    b.ToTable("tes2s");
                });

            modelBuilder.Entity("demoNetCore.Models.demokethua", b =>
                {
                    b.HasBaseType("demoNetCore.Models.Person");

                    b.Property<string>("demokethuaID")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("demokethuatName")
                        .HasColumnType("TEXT");

                    b.ToTable("Person");

                    b.HasDiscriminator().HasValue("demokethua");
                });

            modelBuilder.Entity("demoNetCore.Models.tes2", b =>
                {
                    b.HasOne("demoNetCore.Models.tes1", "tes1")
                        .WithMany("tes2s")
                        .HasForeignKey("tes1ID");

                    b.Navigation("tes1");
                });

            modelBuilder.Entity("demoNetCore.Models.tes1", b =>
                {
                    b.Navigation("tes2s");
                });
#pragma warning restore 612, 618
        }
    }
}
